[package]
name = "Chesnaught"
version = "0.1.0"
authors = ["neverRare <neverrare@proton.me>"]
repository = "https://github.com/neverRare/chesnaught"
edition = "2024"

[dependencies]
rand = "0.9.2"
rustc-hash = "2.1.1"

[profile.release]
lto = true
